[[title]]
= Heat Transfer Simulation

Alejandro Guerra Rodríguez, alejandro.guerrarodriguez@ucr.ac.cr

:doctype: article
:imagesdir: img
:nofooter:
:sectnums:
:stem: latexmath
:toc: left
:xrefstyle: short

This program provides a way to simulate heat transfer in a plate. In a real scenario, a scientist will apply constant heat to the plate borders and track the behavior until equilibrium is reached. This state is achieved when each point of the plate does not change its temperature with time (or the change is under an established margin). For simulation purposes, the plate will be considered as a matrix of `R` rows and `C` columns, with square cells of size `h`. 

[[matrix-heat-simulation]]
.Representation of the plate in the simulation. footnote:[Image retrieved from https://jeisson.ecci.ucr.ac.cr/concurrente/2025b/tareas/#problem_statement[Problem Statement].]
image::plate_example.svg[align=center,link=plate_example.svg]


[[problem-statement]]
== Problem Statement

Each cell's temperature will change after a period `Δt` based on <<heat-equation>>, where each cell depens on:

  . The temperature given by the neighbor cells (excluding diagonals) as stem:[T^{k}_{i-1,j}+T^{k}_{i,j+1}+T^{k}_{i+1,j}+T^{k}_{i,j-1}].
  . Energy lost, distributed to the neighbor cells (excluding diagonals) as stem:[-4T^{k}_{i,j}].
  . Inverse proportionallity with size as stem:[\frac{1}{h^{2}}].
  . The time step as stem:[\Delta t].
  . Thermal diffusivity as stem:[\propto].

[[heat-equation]]
.Heat Transfer Equation
[stem]
++++
T^{k+1}_{i,j} = T^{k}_{i,j}+\frac{\Delta t*\propto }{h^{2}}(T^{k}_{i-1,j}+T^{k}_{i,j+1}+T^{k}_{i+1,j}+T^{k}_{i,j-1}-4T^{k}_{i,j})
++++

[[simulation-details]]
== Simulation workflow

When executed, the simulation reads a work file that contains the input plate and the values needed to perform the simulation in the following order:

  . Plate file path relative to the work file.
  . Time step in seconds.
  . Thermal diffusivity.
  . Dimensions.
  . Thermal sensitivity.

IMPORTANT: If a cell temperature change is lower than the thermal sensitivity, then the cell is at equilibrium. The plate equilibrium is when every cell reaches equilibrium.

.Work file example
[source,txt]
----
plate001.bin  1200  127  1000  2
plate001.bin  1200  127  1000  1.5
plate001.bin  1200  127  1000  1
plate001.bin  1200  127  1000  0.1
plate002.bin    60 0.08   450  0.075
----

For each line, the simulation will be computed. Then, a report file with the work file statistics and one binary file for each plate processed with the resulting state will be generated.

.Report file example
[source,txt]
----
plate001.bin	1200	127	1000	2	2	0000/00/00	00:40:00
plate001.bin	1200	127	1000	1.5	3	0000/00/00	01:00:00
plate001.bin	1200	127	1000	1	4	0000/00/00	01:20:00
plate001.bin	1200	127	1000	0.1	11	0000/00/00	03:40:00
plate002.bin	60	0.08	450	0.075	1	0000/00/00	00:01:00
----

IMPORTANT: The new parameters are the number of states `k` until thermal equilibrium and the time spent (not execution time, but computed with `kΔt`) until equilibrium was reached.

[[user-manual]]
== User Manual

To use this simulation, first be sure to have installed make and gcc installed. Otherwise, do so with the following commands:

[source,bash]
----
sudo apt update
sudo apt install build-essential
----

In the repository, a makefile is provided to facilitate the compilation and execution of the projet. It can be used in the following way:

[source,bash]
----
# To compile the projet
make

# To run the projet with required CLI arguments
make run ARGS='work_directory work_file output_directory thread_number'

# To delete the generated files while compilation
make clean
----

== Error Handling
This project follows the POSIX convention for error codes. All supported codes are listed in <<error-codes>>. Note that the error code is placed in the `errno` variable.

IMPORTANT: The *callee* is responsible for detecting errors. The *caller* is responsible for handling them, including reporting any error messages.


[[error-codes]]
.POSIX Error Codes (retrieved from ChatGPT)
[cols="1,1,3", options="header"]
|===
|Code |Name |Description

|1   |EPERM          |Operation not permitted.
|2   |ENOENT         |No such file or directory.
|3   |ESRCH          |No such process.
|4   |EINTR          |Interrupted system call.
|5   |EIO            |Input/output error.
|6   |ENXIO          |No such device or address.
|7   |E2BIG          |Argument list too long.
|8   |ENOEXEC        |Exec format error.
|9   |EBADF          |Bad file descriptor.
|10  |ECHILD         |No child processes.
|11  |EAGAIN         |Resource temporarily unavailable (non-blocking).
|12  |ENOMEM         |Out of memory.
|13  |EACCES         |Permission denied.
|14  |EFAULT         |Bad address (invalid pointer).
|16  |EBUSY          |Device or resource busy.
|17  |EEXIST         |File exists.
|19  |ENODEV         |No such device.
|20  |ENOTDIR        |Not a directory.
|21  |EISDIR         |Is a directory.
|22  |EINVAL         |Invalid argument.
|24  |EMFILE         |Too many open files (per process limit).
|25  |ENOTTY         |Inappropriate ioctl for device (not a TTY).
|30  |EROFS          |Read-only file system.
|32  |EPIPE          |Broken pipe (peer closed connection).
|35/11 |EWOULDBLOCK |Equivalent to EAGAIN (non-blocking socket).
|36  |ENAMETOOLONG   |File name too long.
|38  |ENOSYS         |Function not implemented.
|39  |ENOTEMPTY      |Directory not empty.
|60/61 |ETIMEDOUT    |Connection timed out.
|104 |ECONNRESET     |Connection reset by peer.
|111 |ECONNREFUSED   |Connection refused.
|113 |EHOSTUNREACH   |No route to host.
|115 |EINPROGRESS    |Operation in progress (non-blocking connect()).
|===


== References

[1] Jeisson Hidalgo. *Concurrent Programming — 2025b, Assignment Description*. 
https://jeisson.ecci.ucr.ac.cr/concurrente/2025b/tareas/#problem_statement